language: node_js

node_js:
  - '0.10'
  - '0.11'
  - '0.12'

before_install:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g cleverstack-cli
  - npm install ncp
  - npm install rimraf
  - npm install bluebird

before_script:
  - mysql -e 'create database test_db;'
  - export NODE_ENV=test
  - export NODE_PATH=./lib/:./modules/
  - node tests/beforeTravis.js
  - cd testProject

services:
  - mysql
